name: McWerewolf
version: '${version}'
main: alian713.mc.mcwerewolf.McWerewolf
api-version: '1.20'
author: 'Alian713'

permissions:
  werewolf.gm:
    description: "Commands only admins should be able to run"
    default: op
  werewolf.player:
    description: "Commands everyone can run"
    default: true

commands:
  host-game:
    description: "Host a game of Werewolf"
    usage: "/host-game"
    permission: werewolf.player
  list-games:
    description: "List all open games of Werewolf"
    usage: "/list-games"
    permission: werewolf.player
  list-players:
    description: "List all players in the game of Werewolf hosted by the specified player"
    usage: "/list-players <Host Player Name>"
    permission: werewolf.player
  cancel-game:
    description: "Cancel the game of Werewolf that you are hosting"
    usage: "/cancel-game"
    permission: werewolf.player
  join-game:
    description: "Join the werewolf game hosted by the specified player"
    usage: "/join-game <Host Player Name>"
    permission: werewolf.player
  leave-game:
    description: "Leave the werewolf game hosted by the specified player"
    usage: "/leave-game <Host Player Name>"
    permission: werewolf.player
  start-game:
    description: "Start the game of Werewolf that you are hosting"
    usage: "/start-game"
    permission: werewolf.player
  night-phase:
    description: "Start the night phase"
    usage: "/night-phase"
    permission: werewolf.player
  day-phase:
    description: "Start the day/discussion phase"
    usage: "/day-phase"
    permission: werewolf.player

  see-player:
    description: "See if the specified player is a werewolf [seer; night phase]"
    usage: "/see-player <Player Name>"
    permission: werewolf.player
  eat-player:
    description: "Eat the specified player [chosen; werewolf; night phase]"
    usage: "/eat-player <Player Name>"
    permission: werewolf.player
  save-player:
    description: "Save the specified player from being killed [medic; night phase]"
    usage: "/save-player <Player Name>"
    permission: werewolf.player
  nom-player:
    description: "Nominate the specified player for being lynching"
    usage: "/nom-player <Player Name>"
    permission: werewolf.player
  run-noms:
    description: "Go through the voting phase for everyone that has been nominated for lynching"
    usage: "/run-noms"
    permission: werewolf.player
  lynch:
    description: "Vote to lynch the player currently on the chopping block"
    usage: "/lynch"
    permission: werewolf.player